runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app

# https://cloud.google.com/appengine/docs/standard/python/tools/built-in-libraries-27

libraries:
- name: enum
  version: "0.9.23"
- name: flask
  version: "0.12"
- name: futures
  version: "3.0.5"
- name: jinja2
  version: "2.6"
- name: six
  version: "1.9.0"
- name: ujson
  version: "1.35"
- name: webob
  version: "1.2.3"
- name: werkzeug
  version: "0.11.10"
- name: yaml
  version: "3.10"
